
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ack-apigatewayv2-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - domainnames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - domainnames/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - routeresponses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - routeresponses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - routes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - stages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - stages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources/status
  verbs:
  - get
  - patch
  - update
