---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-apigatewayv2-reader
  namespace: default
rules:
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - domainnames
  - routes
  - routeresponses
  - stages
  verbs:
  - get
  - list
  - watch
