apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - common
resources:
  - bases/apigatewayv2.services.k8s.aws_domainnames.yaml
  - bases/apigatewayv2.services.k8s.aws_routes.yaml
  - bases/apigatewayv2.services.k8s.aws_routeresponses.yaml
  - bases/apigatewayv2.services.k8s.aws_stages.yaml
